title: Stackbit Ampersand Theme
baseURL: /
params:
  footer:
    content: '&copy; Stackbit-Ampersand. All rights reserved.'
    has_social: true
    links:
      - new_window: true
        text: Made with Stackbit
        url: 'https://www.stackbit.com'
  header:
    has_nav: true
    logo_img: images/logo.png
    title: Stackbit-Test
  layout_style: grid
  palette: red
disableKinds:
  - RSS
